swagger: "2.0"
info:
  description: "ATCOI profile manager docs"
tags:
  - name: User Session
    description: profile, login and login verify api's
  - name: Admin Session 
    description: ""
  - name: Interest
    description: CRUD of interest
  - name: Subinterest
    description: CRUD of interest
  - name: UserInterest
    description: ""
  - name: UserDream
    description: CRUD of dream
schemes:
  - http
  - https
paths:
  /profiles/login:
    post:
      tags:
        - User Session
      summary: Register User and Sends OTP code to mobile number provided in request
      description: "Register user and Request to Send OTP"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          description: "header to specify the api version eg: application/vnd.profilemgr.v1, application/vnd.profilemgr.v2"
          name: Accept
          schema:
            type: string
          required: true
        - in: body
          name: body
          description: Login Request
          required: true
          schema:
            $ref: "#/definitions/LoginRequest"
      responses:
        "200":
          description: OTP code send successfully Sending OTP code for now as we mock SMS service
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /profiles/admin/login:
    post:
      tags:
        - Admin Session
      summary: Register User and Sends OTP code to mobile number provided in request
      description: "Register user and Request to Send OTP"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          description: "header to specify the api version eg: application/vnd.profilemgr.v1, application/vnd.profilemgr.v2"
          name: Accept
          schema:
            type: string
          required: true
        - in: body
          name: body
          description: Login Request
          required: true
          schema:
            $ref: "#/definitions/LoginRequest"
      responses:
        "200":
          description: OTP code send successfully Sending OTP code for now as we mock SMS service
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        "401":
          description: Unauthorized User
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /profiles/login/verify:
    post:
      tags:
        - User Session
        - Admin Session
      summary: Verifies if the otp passed in request is valid for the given mobile number
      description: "Login Request to Verify OTP"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          description: "header to specify the api version eg: application/vnd.profilemgr.v1, application/vnd.profilemgr.v2"
          name: Accept
          schema:
            type: string
          required: true
        - in: body
          name: body
          description: Login Verify Body
          required: true
          schema:
            $ref: "#/definitions/LoginVerifyRequest"
      responses:
        "200":
          description: OTP verification success
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        "409":
          description: Conflict
          schema:
            $ref: "#/definitions/ErrorResponse"
        "422":
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /profiles/admin/users:
    post:
      tags:
        - Admin Session
      summary: Admin will add new user for admin-panel
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          description: "header to specify the api version eg: application/vnd.profilemgr.v1, application/vnd.profilemgr.v2"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - in: body
          name: body
          description: Login Request
          required: true
          schema:
            $ref: "#/definitions/AddRequest"
      responses:
        "200":
          description: Created
          schema:
            $ref: "#/definitions/CreateSuccessResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "401":
          description: Unauthorized User
          schema:
            $ref: "#/definitions/ErrorResponse"
  /profiles/interests:
    post:
      tags:
        - Interest
      summary: Create a new Interest.
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - in: body
          name: body
          description: Request body
          required: true
          schema:
            $ref: "#/definitions/CreateInterestRequest"
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        "201":
          description: Created
          schema:
            $ref: "#/definitions/SuccessResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "401":
          description: Unauthorized User
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      tags:
        - Interest
      summary: Get a list of all interests
      description: ""
      produces:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ListInterestResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /profiles/interests/{interest_id}/subinterests:
    post:
      tags:
        - Subinterest
      summary: Create a new Subinterest.
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - name: interest_id
          in: path
          description: id get from url
          required: true
          type: string
          format: uuid
        - in: body
          name: body
          description: Request body
          required: true
          schema:
            $ref: "#/definitions/CreateSubinterestRequest"
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        "201":
          description: Created
          schema:
            $ref: "#/definitions/SuccessResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "401":
          description: Unauthorized User
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      tags:
        - Subinterest
      summary: Get a list of all subinterests of a interest
      description: ""
      produces:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - in: header
          description: "header to authentication of user eg: eysInR5cCI6IkpXVCJ9.eyOH0._Ds8DCuZ7SxVPGJkZd4 "
          name: Authorization
          schema:
            type: string
          required: true
        - name: interest_id
          in: path
          description: id of interest
          required: true
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ListSubinterestResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /profiles/interests/{interest_id}:
    get:
      tags:
        - Interest
        - Subinterest
      summary: Find interest or subinterest by ID. In case of subinterest parent_id will be present in response.
      description: Returns a single interest or subinterest
      produces:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - name: interest_id
          in: path
          description: id get from url
          required: true
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/InterestObject"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      tags:
        - Interest
      summary: Update an existing Interest.
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - name: interest_id
          in: path
          description: id get from url
          required: true
          type: string
          format: uuid
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/UpdateInterestRequest"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "401":
          description: Unauthorized User
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
        - Interest
        - Subinterest
      summary: Delete a interest or a subinterest By ID
      description: ""
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - name: interest_id
          in: path
          description: id of interest
          required: true
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/SuccessResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "401":
          description: Unauthorized User
          schema:
            $ref: "#/definitions/ErrorResponse"
  /profiles/users/{user_id}/interests:
    post:
      tags:
        - UserInterest
      summary: Create User Interests.
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - name: user_id
          in: path
          description: id get from url
          required: true
          type: string
          format: uuid
        - in: body
          name: body
          description: Request body
          required: true
          schema:
            $ref: "#/definitions/UserInterestRequest"
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        "201":
          description: Created
          schema:
            $ref: "#/definitions/SuccessResponse"
        "401":
          description: Unauthorized User
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      tags:
        - UserInterest
      summary: Get a list of all User Interests
      description: ""
      produces:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - name: user_id
          in: path
          description: id get from url
          required: true
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ListUserInterestResponse"
        "401":
          description: Unauthorized User
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
        - UserInterest
      summary: Deletes user interests By interest or subinterest ID
      description: ""
      consumes:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - name: user_id
          in: path
          description: id of user
          required: true
          type: string
          format: uuid
        - in: body
          name: body
          description: Request body
          required: true
          schema:
            $ref: "#/definitions/UserInterestRequest"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/SuccessResponse"
        "401":
          description: Unauthorized User
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /profiles/interests/{interest_id}/subinterests/{subinterest_id}:
    put:
      tags:
        - Subinterest
      summary: Update an existing Subinterest.
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - name: interest_id
          in: path
          description: id get from url
          required: true
          type: string
          format: uuid
        - name: subinterest_id
          in: path
          description: id get from url
          required: true
          type: string
          format: uuid
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/UpdateSubinterestRequest"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "401":
          description: Unauthorized User
  /profiles/users/{user_id}/dreams:
    post:
      tags:
        - UserDream
      summary: Create User Dream.
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - name: user_id
          in: path
          description: put user_id in url
          required: true
          type: string
          format: uuid
        - in: body
          name: body
          description: Request body
          required: true
          schema:
            $ref: "#/definitions/CreateUserDreamRequest"
      responses:
        "201":
          description: User dream created successfully.
          schema:
            $ref: "#/definitions/CreateResponse"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/ErrorResponse" 
        "401":
          description: Unauthorized User
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      tags:
        - UserDream
      summary: Get a list of all User dreams
      description: ""
      produces:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - name: user_id
          in: path
          description: put user_id in url
          required: true
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ListUserDreamResponse"
        "401":
          description: Unauthorized User
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"  
  /profiles/users/{user_id}/dreams/{dream_id}:
    put:
      tags:
        - UserDream
      summary: Update exsting user dream
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - name: user_id
          in: path
          description: put user_id in url
          required: true
          type: string
          format: uuid
        - name: dream_id
          in: path
          description: put dream_id in url
          required: true
          type: string
          format: uuid
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/UpdateUserDreamRequest"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: bad request
          schema:
            $ref : "#/definitions/ErrorResponse"
        "401":
          description: Unauthorized User
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
        - UserDream
      summary: Deletes user dream with respect to dream_id
      description: ""
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
        - in: header
          description: "authorization header"
          name: Authorization
          schema:
            type: string
          required: true
        - name: user_id
          in: path
          description: put user_id in url
          required: true
          type: string
          format: uuid
        - name: dream_id
          in: path
          description: put dream_id in url
          required: true
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/SuccessResponse"
        "401":
          description: Unauthorized User
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /profiles/config:
    get:
      tags:
        - Config
      summary: Get all profiles
      produces:
        - application/json
      parameters:
        - in: header
          description: "Header for request application/vnd.profilemgr.v1"
          name: Accept
          schema:
            type: string
          required: true
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Config"
definitions:
  UserDreamRequest:
    properties:
      description:
        type: string
        reqiured: true
      valuation:
        type: number
        format: float
        reqiured: true
      image_url:
        type: string
    example:
      - description: "buy ktm duke 125"
        valuation: 117000
        image_url: "https://media.abc.com/ktm-125-duke.jpg"
  UserDream:
    properties:
      id:
        type: string
        format: uuid
        description: dream ID
      user_id:
        type: string
        format: uuid
        description: user ID  
      description:
        type: string
      valuation:
        type: number
        format: float
        description: dream cost
      image_url:
        type: string
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
  ListUserDreamResponse:
    type: object
    properties:
      dreams:
        type: array
        items:
          $ref: "#/definitions/UserDream"
        example:
          - id: "d11002bf-359c-4b42-a73d-6fcac4584c64"
            user_id: "f11002bf-359c-4b42-a73d-6fcac4584c64"
            description: "buy ktm duke 125"
            valuation: 117000
            image_url: "https://media.abc.com/ktm-125-duke.jpg"
            created_at: "2019-03-19T15:13:28.917051+05:30"
            updated_at: "2019-03-19T15:13:28.917051+05:30"     
          - id: "d11002bf-359c-4b42-a73d-6fcac4584c65"
            user_id: "f11002bf-359c-4b42-a73d-6fcac4584c64"
            description: " fly above the iconic peaks of the Himalayas and Mount Everest."
            valuation: 5000000
            image_url: "https://media.abc.com/Himalayas.jpg"
            created_at: "2019-02-06T15:13:28.917051+05:30"
            updated_at: "2019-02-06T15:13:28.917051+05:30"     
  UpdateDream:
    properties:
      description:
        type: string
        reqiured: true
      valuation:
        type: number
        format: float
        reqiured: true
      image_url:
        type: string
    example:
      description: "buy ktm duke 125"
      valuation: 117000
      image_url: "https://media.abc.com/ktm-125-duke.jpg"
  UpdateUserDreamRequest:
    properties:
      dream:
        type: object
        $ref: "#/definitions/UpdateDream"    
  CreateUserDreamRequest:
    properties:
      dream:
        type: object
        $ref: "#/definitions/UpdateDream"     
  ProfileUserRequest:
    properties:
      first_name:
        type: string
        reqiured: true
      last_name:
        type: string
        reqiured: true
      email:
        type: string
        reqiured: true
      dob:
        type: string
        format: date-time
        reqiured: true
    example:
      first_name: "chinmay"
      last_name: "sonawane"
      email: "chinmay@gmail.com"
      dob: "2019-02-10T15:06:36.866Z"
  LoginSendUserRequest:
    properties:
      country_code:
        type: string
        required: true
      mobile_no:
        type: string
        required: true
    example:
      country_code: "+91"
      mobile_no: "8446761311"
  LoginVerifyUserRequest:
    properties:
      country_code:
        type: string
      mobile_no:
        type: string
      otp_code:
        type: string
    required: -mobile_no
      -country_code
      -otp_code
    example:
      country_code: "+91"
      mobile_no: "8446761311"
      otp_code: "123456"
  ErrorResponse:
    properties:
      message:
        type: string
        description: Error message
  SuccessResponse:
    properties:
      message:
        type: string
        description: Success message
  CreateResponse:
    properties:
      message:
        type: string
        description: Success message
      id: 
        type: string
        description: dream id 
  CreateInterest:
    properties:
      name:
        type: string
        required: true
    example:
      name: "sports"
  CreateInterestRequest:
    properties:
      interest:
        type: object
        $ref: "#/definitions/CreateInterest"
  Interest:
    type: object
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
      parent_id:
        type: string
        format: uuid
    example:
      id: "d11002bf-359c-4b42-a73d-6fcac4584c63"
      name: "sports"
      created_at: "2019-02-06T15:13:28.917051+05:30"
      updated_at: "2019-02-06T15:13:28.917051+05:30"
      parent_id: ""
  ListInterestResponse:
    type: object
    properties:
      interests:
        type: array
        items:
          $ref: "#/definitions/Interest"
        example:
          - id: "d11002bf-359c-4b42-a73d-6fcac4584c63"
            name: "sports"
            created_at: "2019-02-06T15:13:28.917051+05:30"
            updated_at: "2019-02-06T15:13:28.917051+05:30"
            parent_id: ""
          - id: "d11002bf-359c-4b42-a73d-6fcac4584c64"
            name: "tech"
            created_at: "2019-02-06T15:13:28.917051+05:30"
            updated_at: "2019-02-06T15:13:28.917051+05:30"
            parent_id: ""
          - id: "d11002bf-359c-4b42-a73d-6fcac4584c65"
            name: "clothing"
            created_at: "2019-02-06T15:13:28.917051+05:30"
            updated_at: "2019-02-06T15:13:28.917051+05:30"
            parent_id: ""
  UpdateInterest:
    properties:
      name:
        type: string
        required: true
    example:
      name: "sports"
  UpdateInterestRequest:
    properties:
      interest:
        type: object
        $ref: "#/definitions/UpdateInterest"
  CreateSubinterest:
    properties:
      name:
        type: string
        required: true
    example:
      name: "cricket"
  CreateSubinterestRequest:
    properties:
      subinterest:
        type: object
        $ref: "#/definitions/CreateSubinterest"
  ListSubinterestResponse:
    type: object
    properties:
      subinterests:
        type: array
        items:
          $ref: "#/definitions/Interest"
        example:
          - id: "d11002bf-359c-4b42-a73d-6fcac4584c73"
            name: "cricket"
            created_at: "2019-02-06T15:13:28.917051+05:30"
            updated_at: "2019-02-06T15:13:28.917051+05:30"
            parent_id: "d11002bf-359c-4b42-a73d-6fcac4584c63"
          - id: "d11002bf-359c-4b42-a73d-6fcac4584c74"
            name: "football"
            created_at: "2019-02-06T15:13:28.917051+05:30"
            updated_at: "2019-02-06T15:13:28.917051+05:30"
            parent_id: "d11002bf-359c-4b42-a73d-6fcac4584c63"
          - id: "d11002bf-359c-4b42-a73d-6fcac4584c75"
            name: "baseball"
            created_at: "2019-02-06T15:13:28.917051+05:30"
            updated_at: "2019-02-06T15:13:28.917051+05:30"
            parent_id: "d11002bf-359c-4b42-a73d-6fcac4584c63"
  UpdateSubinterest:
    properties:
      name:
        type: string
        reqiured: true
    example:
      name: "baseball"
  UpdateSubinterestRequest:
    properties:
      subinterest:
        type: object
        $ref: "#/definitions/UpdateSubinterest"
  InterestObject:
    type: object
    properties:
      interest:
        $ref: "#/definitions/Interest"
  RequestUserInterest:
    properties:
      interest_id:
        type: string
        format: uuid
        required: true
  UserInterestRequest:
    type: object
    properties:
      interests:
        type: array
        items:
          $ref: "#/definitions/RequestUserInterest"
        example:
          - interest_id: "d11002bf-359c-4b42-a73d-6fcac4584c64"
          - interest_id: "d11002bf-359c-4b42-a73d-6fcac4584c65"
          - interest_id: "d11002bf-359c-4b42-a73d-6fcac4584c66"
  UserInterest:
    properties:
      id:
        type: string
        format: uuid
        description: interest ID
      name:
        type: string
  ListUserInterestResponse:
    type: object
    properties:
      interests:
        type: array
        items:
          $ref: "#/definitions/UserInterest"
        example:
          - id: "d11002bf-359c-4b42-a73d-6fcac4584c64"
            name: "tech"
          - id: "d11002bf-359c-4b42-a73d-6fcac4584c65"
            name: "football"
          - id: "d11002bf-359c-4b42-a73d-6fcac4584c66"
            name: "cricket"
  ProfileRequest:
    type: object
    properties:
      user:
        type: object
        $ref: "#/definitions/ProfileUserRequest"
  LoginRequest:
    type: object
    properties:
      user:
        type: object
        $ref: "#/definitions/LoginSendUserRequest"
  LoginVerifyRequest:
    type: object
    properties:
      user:
        type: object
        $ref: "#/definitions/LoginVerifyUserRequest"
  LoginUserResponse:
    properties:
      id:
        type: string
        format: uuid
      country_code:
        type: string
      mobile_no:
        type: string
      profile:
        type: integer
      token:
        type: string
    example:
      id: "d192ad8e-8d2a-4d96-af1d-3b9eb15c05f1"
      country_code: "+91"
      mobile_no: "9876543210"
      profile: 1
      token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2Nlc3NUb2tlbiI6ImxldmVsMSIsIkVtYWlsIjoiYW51akBqb3Noc29mdHdhcmUuY29tIiwiTm9WUE4iOiJDT05GSUciLCJPcmdJRCI6IjNmOTNhZDQ1LTZhOWUtNDVkMC04ZGQxLWM1OTk2MDViZTUzNCIsIlByb2ZpbGUiOiJPd25lciIsImV4cCI6MTU1MzE1NDE4OX"
  LoginConfigResponse:
    properties:
      invite_only:
        type: Boolean
    example:
      invite_only: true
  LoginResponse:
    type: object
    properties:
      user:
        type: object
        $ref: "#/definitions/LoginUserResponse"
      config:
        type: object
        $ref: "#/definitions/LoginConfigResponse"
  AddRequest:
    type: object
    properties:
      user:
        type: object
        $ref: "#/definitions/AddUserRequest"
  AddUserRequest:
    properties:
      country_code:
        type: string
        required: true
      mobile_no:
        type: string
        required: true
      profile:
        type: integer
        format: int32
        reqiured: true
    example:
      country_code: "+91"
      mobile_no: "8446761311"
      profile: 4
  CreateSuccessResponse:
    properties:
      message:
        type: string
        description: Success message
      id: 
        type: string
        format: uuid
        description: Created ID
  Config:
    type: object
    properties:
      profiles:
        type: array
        items:
        example:
        - value: 1 
          name: "End User"
        - value: 2
          name: "Data Entry"  
        - value: 4
          name: "Moderator"
        - value: 8 
          name: "Admin"
